--1.  Create an index on the customer(last_name) column. 
create index idx_customer_lastname
on customer(last_name);

--2. Create an index on the invoice(invoice_date) column.
create index idx_invoice_date
on invoice(invoice_date);

--3. Create a composite index on invoice(customer_id, invoice_date). 
create index idx_invoice_id_date
on invoice(customer_id,invoice_date);

--4. Drop the index created on customer(last_name).
drop index idx_customer_lastname;

--5.Explain in one sentence: Why is an index useful on the invoice_date column? 
-- because of invoice_date can be much more huge so using index get answers more faster

--6.
"""
Show each customer's: 
 First Name  
 Last Name  
 Total Invoices  
 Total Amount Spent 
"""
select 
	c.first_name,
	c.last_name,
	count(i.invoice_id) as total_invoices,
	sum(i.total) as total_amount_spent
from customer c
join invoice i
on c.customer_id = i.customer_id
group by 1,2;

--7.  
"""
Show each genre with: 
 Total Tracks  
 Average Track Length  
"""
select 
	g.name,
	count(t.track_id) as total_tracks,
	avg(t.milliseconds) as average_track_length
from genre g
join track t
on g.genre_id = t.genre_id
group by 1;

--8.
"""
Show each artist with: 
 Total Albums  
 Total Tracks 
"""
select 
	ar.name,
	count(distinct al.album_id) as total_albums,
	count(t.track_id) as total_tracks
from artist ar
join album al
on ar.artist_id = al.artist_id
join track t
on al.album_id = t.album_id
group by 1;

--9. 
"""
Show each country with: 
 Number of Customers  
 Total Revenue  
 Average Invoice Value 
"""
select
	billing_country,
	count(distinct customer_id) as Numbers_of_customer,
	sum(total) as Total_revenue,
	avg(total) as Average_invoice_value
from invoice 
group by 1;

--10. 
"""
Show each employee with: 
 Number of Customers Assigned  
 Total Revenue Generated by their Customers 
"""
select 
	e.employee_id,
	count(distinct c.customer_id) as num_of_cus_assigned,
	sum(i.total) as total_rev_gen_by_cust
from employee e
join customer c 
on e.employee_id = c.support_rep_id
join invoice i
on c.customer_id = i.customer_id
group by 1

--11. 
"""
Show each media type with: 
 Total Tracks  
 Total Sales Amount  
"""
select 
	mt.name,
	count(distinct t.track_id) as total_tracks,
	sum(i.total) as total_sales_amt
from media_type mt

join track t
on mt.media_type_id = t.media_type_id

join invoice_line il
on t.track_id = il.track_id

join invoice i
on il.invoice_id = i.invoice_id

group by 1;

--12. 
"""
Show each playlist with: 
 Number of Tracks  
 Total Duration (Minutes) 
"""
select 
	p.name,
	count(distinct t.track_id) as num_of_tracks,
	sum(t.milliseconds/1000/60) as Total_duration_min
from playlist p

join playlist_track pt
on p.playlist_id = pt.playlist_id

join track t
on pt.track_id = t.track_id

group by 1;

--13.  
"""
Show every customer with a new column: 
Customer Type 

Rules: 
 Total Spent > 45 → Premium  
 25–45 → Regular  
 Below 25 → Basic  
(Use CASE.)
"""
SELECT
    c.customer_id,
    SUM(i.total) AS total_spent,
	
    CASE
        WHEN SUM(i.total) > 45 THEN 'Premium'
        WHEN SUM(i.total) BETWEEN 25 AND 45 THEN 'Regular'
        ELSE 'Basic'
    END AS customer_type
	
FROM customer c

JOIN invoice i
ON c.customer_id = i.customer_id
GROUP BY c.customer_id;

--14. 
"""
Show each genre with: 
 Rock Track Count  
 Non-Rock Track Count  
(Use Conditional Aggregation.)
"""
SELECT
    g.name,

    COUNT(
        CASE
            WHEN g.name = 'Rock' THEN t.track_id
        END
    ) AS rock_track_count,

    COUNT(
        CASE
            WHEN g.name <> 'Rock' THEN t.track_id
        END
    ) AS non_rock_track_count

FROM genre g

JOIN track t
ON g.genre_id = t.genre_id

GROUP BY
    g.genre_id,
    g.name;

--15. 
"""
Show monthly revenue. 
Return: 
 Year  
 Month  
 Total Revenue 
"""
SELECT
    EXTRACT(YEAR FROM invoice_date) AS year,
    EXTRACT(MONTH FROM invoice_date) AS month,
    SUM(total) AS total_revenue
FROM invoice

GROUP BY 1,2
ORDER BY 1,2

--16. 
"""
Show yearly revenue. 
Return: 
 Year  
 Revenue 
"""
select 
	extract (year from invoice_date) as year,
	sum(total) as revenue
from invoice

group by 1;

--17.  
"""
Show each artist with: 
 Total Sales  
 Percentage Contribution to Overall Sales  

Example: 
| Artist | Sales | Sales % |
"""
SELECT
    ar.name,
    SUM(il.unit_price * il.quantity) AS sales,

    ROUND(
        (
            SUM(il.unit_price * il.quantity) * 100.0
            / SUM(SUM(il.unit_price * il.quantity)) OVER ()
        )::numeric,
        2
    ) AS per_sales

FROM artist ar

JOIN album al
ON ar.artist_id = al.artist_id

JOIN track t
ON al.album_id = t.album_id

JOIN invoice_line il
ON t.track_id = il.track_id

GROUP BY
    ar.artist_id,
    ar.name

ORDER BY sales DESC;

--18. 
"""
Show each country with its percentage contribution to total revenue. 

Example: 
| Country | Revenue | Revenue % |
"""
SELECT
    billing_country,
    SUM(total) AS revenue,
    ROUND((SUM(total) * 100.0 / SUM(SUM(total)) OVER ())::numeric,2) AS per_country
FROM invoice

GROUP BY 1
ORDER BY 2 DESC;

--19. 
"""
Create a report showing: 
 Genre  
 Total Sales  
 Number of Customers who purchased that Genre  
"""
select 
	g.name,
	sum(il.unit_price * il.quantity) as total_sales,
	count(distinct c.customer_id) as per_by_cus
from genre g

join track t
on g.genre_id = t.genre_id 

join invoice_line il
on t.track_id = il.track_id

join invoice i
on il.invoice_id = i.invoice_id

join customer c
on i.customer_id = c.customer_id

group by 1

--20. 
"""
Create a final business report returning: 
 Artist Name  
 Total Albums  
 Total Tracks  
 Total Sales  
 Rank based on Total Sales 
"""
select 
	ar.name,
	count(distinct al.album_id) as total_albums,
	count(distinct t.track_id) as total_tracks,
	sum(il.unit_price * il.quantity) as total_Sales,
	rank() over (order by sum(il.unit_price * il.quantity))
from artist ar

join album al
on ar.artist_id = al.artist_id

join track t
on al.album_id = t.album_id

join invoice_line il
on t.track_id = il.track_id

group by 1
order by 4
